apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-app
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
      - name: admin-app-container
        image: repo1.azurecr.io/admin-app-image
        ports:
        - containerPort: 8082
